create table disciplina_id_seq (next_val bigint) engine=InnoDB;
insert into disciplina_id_seq values ( 1 );
create table disciplina_master_seq (next_val bigint) engine=InnoDB;
insert into disciplina_master_seq values ( 1 );
create table disciplina_zi_seq (next_val bigint) engine=InnoDB;
insert into disciplina_zi_seq values ( 1 );
create table disciplina_id (id integer not null, numar_activitati_aplicative_asistate integer not null, numar_credite_transferabile integer not null, numar_ore_activitati_autoinstruire integer not null, numar_ore_activitati_tutorat integer not null, numar_teme_de_control integer not null, semestru integer not null, volum_ore_necesara_pregatiri_individuale integer not null, volum_ore_necesare_activitatilor_partial_asistate integer not null, categorie_formativa_licenta varchar(255), cod varchar(255), forma_evaluare varchar(255), nume varchar(255), primary key (id)) engine=InnoDB;
create table disciplina_master (id integer not null, numar_credite_transferabile integer not null, numar_ore_curs integer not null, numar_ore_laborator integer not null, numar_ore_proiect integer not null, numar_ore_seminar integer not null, semestru integer not null, volum_ore_necesara_pregatiri_individuale integer not null, volum_ore_necesare_activitatilor_partial_asistate integer not null, categorie_formativa_master varchar(255), cod varchar(255), forma_evaluare varchar(255), nume varchar(255), primary key (id)) engine=InnoDB;
create table disciplina_zi (id integer not null, numar_credite_transferabile integer not null, numar_ore_curs integer not null, numar_ore_laborator integer not null, numar_ore_proiect integer not null, numar_ore_seminar integer not null, semestru integer not null, volum_ore_necesara_pregatiri_individuale integer not null, volum_ore_necesare_activitatilor_partial_asistate integer not null, categorie_formativa_licenta varchar(255), cod varchar(255), forma_evaluare varchar(255), nume varchar(255), primary key (id)) engine=InnoDB;
create table plan_invatamant_licenta_seq (next_val bigint) engine=InnoDB;
insert into plan_invatamant_licenta_seq values ( 1 );
create table plan_invatamant_master_seq (next_val bigint) engine=InnoDB;
insert into plan_invatamant_master_seq values ( 1 );
create table plan_invatamant_licenta (an_calendaristic integer not null, cod_domeniu_de_licenta integer not null, cod_domeniu_fundamental integer not null, cod_ramura_de_stiinta integer not null, cod_studii integer not null, durata_studii_licenta integer not null, id integer not null, invatamant_distanta bit not null, ciclu varchar(255), codul_programului_de_studii varchar(255), domeniu_de_licenta varchar(255), domeniu_fundamental varchar(255), facultate varchar(255), program_de_studii_licenta varchar(255), ramura_de_stiinta varchar(255), universitate varchar(255), primary key (id)) engine=InnoDB;
create table plan_invatamant_licenta_lista_disciplina_id (lista_disciplina_id_id integer not null, plan_invatamant_licenta_id integer not null) engine=InnoDB;
create table plan_invatamant_licenta_lista_disciplina_zi (lista_disciplina_zi_id integer not null, plan_invatamant_licenta_id integer not null) engine=InnoDB;
create table plan_invatamant_master (an_calendaristic integer not null, cod_domeniu_fundamental integer not null, cod_domeniu_studii_master integer not null, cod_ramura_de_stiinta integer not null, durata_studiilor integer not null, id integer not null, ciclu varchar(255), codul_programului_de_studii varchar(255), domeniu_de_licenta varchar(255), domeniu_fundamental varchar(255), domeniu_studii_master varchar(255), facultate varchar(255), format_invatamant varchar(255), program_master varchar(255), ramura_de_stiinta varchar(255), universitate varchar(255), primary key (id)) engine=InnoDB;
create table plan_invatamant_master_lista_disciplina_master (lista_disciplina_master_id integer not null, plan_invatamant_master_id integer not null) engine=InnoDB;
create table privileges (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table privileges_seq (next_val bigint) engine=InnoDB;
insert into privileges_seq values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table roles_privileges (privilege_id bigint not null, role_id bigint not null, primary key (privilege_id, role_id)) engine=InnoDB;
create table roles_seq (next_val bigint) engine=InnoDB;
insert into roles_seq values ( 1 );
create table users (enabled bit not null, id bigint not null, email varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table plan_invatamant_licenta_lista_disciplina_id add constraint UK_bhhcf5l4791msd6vyd4cruqmy unique (lista_disciplina_id_id);
alter table plan_invatamant_licenta_lista_disciplina_zi add constraint UK_h7ctogkfa6jb9oiw4whs391t4 unique (lista_disciplina_zi_id);
alter table plan_invatamant_master_lista_disciplina_master add constraint UK_9qrvdjmoeucwpw6y2st5cy9r6 unique (lista_disciplina_master_id);
alter table privileges add constraint UK_m2tnonbcaquofx1ccy060ejyc unique (name);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table plan_invatamant_licenta_lista_disciplina_id add constraint FK98a6xx2t95qcw9ic74gdxrcel foreign key (lista_disciplina_id_id) references disciplina_id (id);
alter table plan_invatamant_licenta_lista_disciplina_id add constraint FKtnkawm1owbfopnhb4ml3x1wl foreign key (plan_invatamant_licenta_id) references plan_invatamant_licenta (id);
alter table plan_invatamant_licenta_lista_disciplina_zi add constraint FK2o1pc5jacd6lopnm5xonbgkh2 foreign key (lista_disciplina_zi_id) references disciplina_zi (id);
alter table plan_invatamant_licenta_lista_disciplina_zi add constraint FKhkulvmwg554dtey3wwr6frmu4 foreign key (plan_invatamant_licenta_id) references plan_invatamant_licenta (id);
alter table plan_invatamant_master_lista_disciplina_master add constraint FKnbqj78708fc2vajj68pwwaumb foreign key (lista_disciplina_master_id) references disciplina_master (id);
alter table plan_invatamant_master_lista_disciplina_master add constraint FK7p8ygvuabvvk2qm93fk0oe78u foreign key (plan_invatamant_master_id) references plan_invatamant_master (id);
alter table roles_privileges add constraint FK5duhoc7rwt8h06avv41o41cfy foreign key (privilege_id) references privileges (id);
alter table roles_privileges add constraint FK629oqwrudgp5u7tewl07ayugj foreign key (role_id) references roles (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
create table disciplina_id_seq (next_val bigint) engine=InnoDB;
insert into disciplina_id_seq values ( 1 );
create table disciplina_master_seq (next_val bigint) engine=InnoDB;
insert into disciplina_master_seq values ( 1 );
create table disciplina_zi_seq (next_val bigint) engine=InnoDB;
insert into disciplina_zi_seq values ( 1 );
create table disciplina_id (id integer not null, numar_activitati_aplicative_asistate integer not null, numar_credite_transferabile integer not null, numar_ore_activitati_autoinstruire integer not null, numar_ore_activitati_tutorat integer not null, numar_teme_de_control integer not null, semestru integer not null, volum_ore_necesara_pregatiri_individuale integer not null, volum_ore_necesare_activitatilor_partial_asistate integer not null, categorie_formativa_licenta varchar(255), cod varchar(255), forma_evaluare varchar(255), nume varchar(255), primary key (id)) engine=InnoDB;
create table disciplina_master (id integer not null, numar_credite_transferabile integer not null, numar_ore_curs integer not null, numar_ore_laborator integer not null, numar_ore_proiect integer not null, numar_ore_seminar integer not null, semestru integer not null, volum_ore_necesara_pregatiri_individuale integer not null, volum_ore_necesare_activitatilor_partial_asistate integer not null, categorie_formativa_master varchar(255), cod varchar(255), forma_evaluare varchar(255), nume varchar(255), primary key (id)) engine=InnoDB;
create table disciplina_zi (id integer not null, numar_credite_transferabile integer not null, numar_ore_curs integer not null, numar_ore_laborator integer not null, numar_ore_proiect integer not null, numar_ore_seminar integer not null, semestru integer not null, volum_ore_necesara_pregatiri_individuale integer not null, volum_ore_necesare_activitatilor_partial_asistate integer not null, categorie_formativa_licenta varchar(255), cod varchar(255), forma_evaluare varchar(255), nume varchar(255), primary key (id)) engine=InnoDB;
create table plan_invatamant_licenta_seq (next_val bigint) engine=InnoDB;
insert into plan_invatamant_licenta_seq values ( 1 );
create table plan_invatamant_master_seq (next_val bigint) engine=InnoDB;
insert into plan_invatamant_master_seq values ( 1 );
create table plan_invatamant_licenta (an_calendaristic integer not null, cod_domeniu_de_licenta integer not null, cod_domeniu_fundamental integer not null, cod_ramura_de_stiinta integer not null, cod_studii integer not null, durata_studii_licenta integer not null, id integer not null, invatamant_distanta bit not null, ciclu varchar(255), codul_programului_de_studii varchar(255), domeniu_de_licenta varchar(255), domeniu_fundamental varchar(255), facultate varchar(255), program_de_studii_licenta varchar(255), ramura_de_stiinta varchar(255), universitate varchar(255), primary key (id)) engine=InnoDB;
create table plan_invatamant_licenta_lista_disciplina_id (lista_disciplina_id_id integer not null, plan_invatamant_licenta_id integer not null) engine=InnoDB;
create table plan_invatamant_licenta_lista_disciplina_zi (lista_disciplina_zi_id integer not null, plan_invatamant_licenta_id integer not null) engine=InnoDB;
create table plan_invatamant_master (an_calendaristic integer not null, cod_domeniu_fundamental integer not null, cod_domeniu_studii_master integer not null, cod_ramura_de_stiinta integer not null, durata_studiilor integer not null, id integer not null, ciclu varchar(255), codul_programului_de_studii varchar(255), domeniu_de_licenta varchar(255), domeniu_fundamental varchar(255), domeniu_studii_master varchar(255), facultate varchar(255), format_invatamant varchar(255), program_master varchar(255), ramura_de_stiinta varchar(255), universitate varchar(255), primary key (id)) engine=InnoDB;
create table plan_invatamant_master_lista_disciplina_master (lista_disciplina_master_id integer not null, plan_invatamant_master_id integer not null) engine=InnoDB;
create table privileges (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table privileges_seq (next_val bigint) engine=InnoDB;
insert into privileges_seq values ( 1 );
create table roles (id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table roles_privileges (privilege_id bigint not null, role_id bigint not null, primary key (privilege_id, role_id)) engine=InnoDB;
create table roles_seq (next_val bigint) engine=InnoDB;
insert into roles_seq values ( 1 );
create table users (enabled bit not null, id bigint not null, email varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table users_roles (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table plan_invatamant_licenta_lista_disciplina_id add constraint UK_bhhcf5l4791msd6vyd4cruqmy unique (lista_disciplina_id_id);
alter table plan_invatamant_licenta_lista_disciplina_zi add constraint UK_h7ctogkfa6jb9oiw4whs391t4 unique (lista_disciplina_zi_id);
alter table plan_invatamant_master_lista_disciplina_master add constraint UK_9qrvdjmoeucwpw6y2st5cy9r6 unique (lista_disciplina_master_id);
alter table privileges add constraint UK_m2tnonbcaquofx1ccy060ejyc unique (name);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table plan_invatamant_licenta_lista_disciplina_id add constraint FK98a6xx2t95qcw9ic74gdxrcel foreign key (lista_disciplina_id_id) references disciplina_id (id);
alter table plan_invatamant_licenta_lista_disciplina_id add constraint FKtnkawm1owbfopnhb4ml3x1wl foreign key (plan_invatamant_licenta_id) references plan_invatamant_licenta (id);
alter table plan_invatamant_licenta_lista_disciplina_zi add constraint FK2o1pc5jacd6lopnm5xonbgkh2 foreign key (lista_disciplina_zi_id) references disciplina_zi (id);
alter table plan_invatamant_licenta_lista_disciplina_zi add constraint FKhkulvmwg554dtey3wwr6frmu4 foreign key (plan_invatamant_licenta_id) references plan_invatamant_licenta (id);
alter table plan_invatamant_master_lista_disciplina_master add constraint FKnbqj78708fc2vajj68pwwaumb foreign key (lista_disciplina_master_id) references disciplina_master (id);
alter table plan_invatamant_master_lista_disciplina_master add constraint FK7p8ygvuabvvk2qm93fk0oe78u foreign key (plan_invatamant_master_id) references plan_invatamant_master (id);
alter table roles_privileges add constraint FK5duhoc7rwt8h06avv41o41cfy foreign key (privilege_id) references privileges (id);
alter table roles_privileges add constraint FK629oqwrudgp5u7tewl07ayugj foreign key (role_id) references roles (id);
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles (id);
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users (id);
